CREATE TABLE CLIENTE_USUARIO
(
  CODIGO_USUARIO NUMBER NOT NULL,
  CODIGO_PJ NUMBER,
  CODIGO_PF NUMBER
)
;

ALTER TABLE CLIENTE_USUARIO
ADD CONSTRAINT COD_USER_PF FOREIGN KEY
(
  CODIGO_PF
)
REFERENCES PESSOA_FISICA
(
CODIGO
) ENABLE
;

ALTER TABLE CLIENTE_USUARIO
ADD CONSTRAINT COD_USER_PJ FOREIGN KEY
(
  CODIGO_PJ
)
REFERENCES PESSOA_JURIDICA
(
CODIGO
) ENABLE
;

ALTER TABLE CLIENTE_USUARIO
ADD CONSTRAINT COD_USER_USER FOREIGN KEY
(
  CODIGO_USUARIO
)
REFERENCES USUARIO
(
CODIGO
) ENABLE
;

insert into CLIENTE_USUARIO values(1,4,null);
insert into CLIENTE_USUARIO values(3,2,null);
